spring:
  mvc:
    static-path-pattern: static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/xiaox?useUnicode=true&characterEncoding=utf8
    password: 123456
    username: root
server:
  port: 8080
mybatis:
  mapper-locations: mapper/*Mapper

